/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    HeadBar: typeof import('./src/components/HeadBar.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuBtn: typeof import('./src/components/MenuBtn.vue')['default']
    MenuFooter: typeof import('./src/components/MenuFooter.vue')['default']
    MenuSet: typeof import('./src/components/MenuSet.vue')['default']
    MenuTop: typeof import('./src/components/MenuTop.vue')['default']
    NoData: typeof import('./src/components/NoData.vue')['default']
    Top: typeof import('./src/components/Top.vue')['default']
  }
}
